### ISSUE TITLE
Add year introduced and year stopped being supported fields

### ISSUE THREAD

**Issue by paradite** [paradite/frontend-encyclopedia#2]

**Comment by yefreescoding** [comment]
I'm eager to contribute to this repository; I believe it's an excellent project idea for newcomers! 😁 Regarding this issue, could you provide more details on how to incorporate the 'year introduced' and 'year stopped being supported' fields into the data.json?

**Comment by paradite** [comment]
> I'm eager to contribute to this repository; I believe it's an excellent project idea for newcomers! 😁 Regarding this issue, could you provide more details on how to incorporate the 'year introduced' and 'year stopped being supported' fields into the data.json?

This would involve adding two optional fields in each item in `data.json`, year_created, and year_deprecated. 

The value of the fields would be number, such as 2018, 2023.

The first PR should come with updates to the scripts to display this information. For example: 

- jQuery - Library (1999 - now)
- BEM - CSS Methodologies (2008 - 2020)

(Above is just an example of format, not real data, you need to include sources for the data)

**Comment by paradite** [comment]
closed via #4
