### ISSUE TITLE
Add author

### ISSUE THREAD

**Issue by paradite** [paradite/frontend-encyclopedia#24]
We may need two more optional fields: `author` as string and `author_url` as an URL.

Also need to update `generate.js` to render the fields

**Comment by RamGoel** [comment]
Hi @paradite , I would like to take it up. Do you have any design in mind for rendering the fields

**Comment by paradite** [comment]
> Hi @paradite , I would like to take it up. Do you have any design in mind for rendering the fields

Yes. PR welcome. 

No design yet, but maybe something like:

- [React](https://react.dev/): Framework, Library, by [Facebook](https://opensource.fb.com/) ([2013](https://www.youtube.com/watch?v=GW0rj4sNH2w))
- [Vue.js](https://vuejs.org/): Framework by [Evan You](https://evanyou.me/) ([2014](https://blog.evanyou.me/2014/02/11/first-week-of-launching-an-oss-project/))

We will probably use a different design for eventual website.

For `author`, we would like to use the name that the person prefers to be identified with, or the name of the organization behind it.
