### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by ccoVeille** [paradite/frontend-encyclopedia#47]
I'm unsure from where you got your data.

But could you add a license to your project? 

So I could add it to my own project without risk.

MIT license would be appreciated

Thanks

**Comment by ccoVeille** [comment]
My project https://github.com/ccoVeille/jargon

And the related issue where I'm tracking your project https://github.com/ccoVeille/jargon/issues/7

**Comment by paradite** [comment]
https://github.com/paradite/frontend-encyclopedia/blob/main/LICENSE

**Comment by ccoVeille** [comment]
Perfect Thanks 🎉🥰
